### ISSUE TITLE
what are these modules trying to import?

### ISSUE THREAD

**Issue by anthonymobile** [BrightLedSigns/pyledsign#2]
each of these modules is importing 

`from ledsign import LedSign, LedSignFactory`

where is this coming from? no reference to it anywhere in the docs or elsewhere in the code and google doesnt turn up anything obvious.

**Comment by budgetneon** [comment]
The LedSign and LedSignFactory classes are coming from:

https://github.com/BrightLedSigns/pyledsign/blob/master/ledsign/__init__.py

It's done that way because the intention is that the library support multiple types of Led Signs.

**Comment by anthonymobile** [comment]
doh! thanks! working beautifully now!
