### ISSUE TITLE
sendcmd functions

### ISSUE THREAD

**Issue by anthonymobile** [BrightLedSigns/pyledsign#4]
Can you shed a little more light on what 'runslots','settime','setcountdown' do?

**Comment by BrightLedSigns** [comment]
runslots wasn't ever implemented.

settime should work 

# You can supply the string "now", and it will sync the sign's clock  
# to the time on the computer running  this api.

# You can also supply an integer representing the time and date
# as unix epoch seconds.  The perl "time" function, for example, returns
# this type of value"

setcountdown should work as well.  The docs from the original Perl code might be helpful. See https://github.com/BrightLedSigns/LedSign/blob/9ec522b5ed2d680dc678cebe6b1557844dc749ae/LedSign::Mini.md (scroll down to setcountdown).

I haven't touched either the Perl or Python versions of these for years, so my memory is a bit foggy on them.

Thanks!
